# Generated by Django 5.0.3 on 2024-06-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_songs_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
