# Generated by Django 5.0.3 on 2024-06-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_songs_file_alter_songs_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
